java_test(
    name = "JsonTest",
    srcs = ["JsonTest.java"],
    test_class = "com.github.liucijus.json.JsonTest",
    deps = [
        "//src/main/java/com/github/liucijus/json",
        "@junit_junit",
    ],
)
