java_test(
    name = "JsonFormatterTest",
    srcs = [
        "JsonDriver.java",
        "JsonFormatterTest.java",
    ],
    test_class = "com.github.liucijus.json.JsonFormatterTest",
    deps = [
        "//src/main/java/com/github/liucijus/json",
        "@junit_junit",
    ],
)

java_test(
    name = "JsonTransformerTest",
    srcs = [
        "JsonDriver.java",
        "JsonTransformerTest.java",
    ],
    test_class = "com.github.liucijus.json.JsonTransformerTest",
    deps = [
        "//src/main/java/com/github/liucijus/json",
        "@junit_junit",
    ],
)
